project:
  type: website

website:
  title: "Keifer Lee"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - href: project.qmd
        text: Not Research
      - contact.qmd


format:
  html:
    theme:
      light: cosmo
      dark: vapor
    css: styles.css
    toc: true
    html-math-method: katex



