project:
  type: website

website:
  title: "Keifer Lee"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - research.qmd
      - href: project.qmd
        text: Not Research
      - href: contact.qmd
        text: Contact


format:
  html:
    theme:
      light: cosmo
      dark: vapor
    favicon: "resources/logo.jpg"
    css: styles.css
    toc: true
    html-math-method: katex



